omar-dulaimi/prisma-zod-generator

- src/transformer.ts
Making sure relative path uses POSIX seperators
> This PR fixes the issue where relative paths generated for prisma-client imports can include a backslash ```\``` which is being ignored as a character and thus resulting in an unusable import. The change makes sure that relative path uses POSIX separators instead of Windows separators by removing the existing separators and replacing them with POSIX separators 
> Issue: #9 
Also my first OSS PR, please give feedback if anything is missing/incomplete, thanks! :)
> Fix broken prisma-client import on windows

- src/transformer.ts
Fixes generating decimal fields, as they are currently getting ignored.
Note that this PR considers decimals as numbers, in the future decimal.js support may get added based on users feedback.
> fix generating decimal fields

- README.md
- package-lock.json
- package.json
- prisma/schema.prisma
- src/transformer.ts
Currently Prisma's `BigInt` is not parsed. For instance if we extend the `Post` model with likes:
```prisma
model Post {
id        Int      @id @default(autoincrement())
createdAt DateTime @default(now())
updatedAt DateTime @updatedAt
title     String
content   String?
published Boolean  @default(false)
viewCount Int      @default(0)
author    User?    @relation(fields: [authorId], references: [id])
authorId  Int?
likes     BigInt
}
```
One of the results is:
```typescript
const Schema: z.ZodType<Prisma.PostCreateInput> = z
.object({
createdAt: z.bigint().optional(),
updatedAt: z.bigint().optional(),
title: z.string(),
content: z.union([z.string(), z.bigint()]).optional().nullable(),
published: z.bigint().optional(),
viewCount: z.number().optional(),
author: z.bigint().optional(),
}) …
```
> Added support for BigInt

- src/transformer.ts
Adding '.strict()' to the Zod objects within a union type, which appears to keep Zod from stripping properties via non-matching elements of the union.
Not sure if there are reasons to avoid `strict` here. If so, this PR may not be an appropriate solution for the problem. Additionally, this seems like questionable behavior on Zod's part and thus the "real fix" may be within Zod.
Fixes https://github.com/omar-dulaimi/prisma-zod-generator/issues/16
> strict() on zod objects within union

- README.md
- prisma/schema.prisma
- src/helpers.ts
- src/helpers/aggregate-helpers.ts
- src/helpers/helpers.ts
- src/helpers/index.ts
- src/helpers/mongodb-helpers.ts
- src/helpers/select-helpers.ts
- src/prisma-generator.ts
- src/transformer.ts
Hi Omar I'm BitPhoenix, it's a pleasure to meet you. I wanted to start off by thanking you for creating such an awesome package! It's very useful and has helped me a lot. I really appreciate the hard work you continue to put into it.
My apologies that the refactor and fix are in one pull review, and that the commits are larger than normal. I'll make sure to separate them in the future. 
Since this is quite a big pull request, please let me know if you'd like to hop on a voice chat to go through the changes together, in case that would help make things easier. 
- Support select: https://github.com/omar-dulaimi/prisma-trpc-generator/issues/13
- Support [select relation fields](https://www.prisma.io/docs/concepts/components/prisma-client/select-fields#include-relations-and-select-relation-fie …
> Refactor + select support

- src/transformer.ts
I Found the bug about `OrderByAggregateInput`. It will used wrong type name, when I generate.
It shouldn't add `Type` after `OrderByAggregateInput` type.
So, I strictly checked `endsWith`.
Sorry for not checking all generated type.
> Fix error type name for OrderByAggregateInput

- prisma/schema.prisma
- src/helpers/helpers.ts
- src/helpers/include-helpers.ts
- src/helpers/modelArgs-helpers.ts
- src/helpers/select-helpers.ts
- src/transformer.ts
Hi @omar-dulaimi
Thanks for creating this useful package. This is my first contribution to an open-source project. Hope my PR  will be good enough to contribute to this project.
Here are the things I have added or changed to make things work.
- I added `isGenerateInclude` flag to control `include field` on schema. The default value of the flags is false.
- Since we have now two flags `(select and include)`, I am required to move the `generateModelArgsInputObjectTypes` function from `select-helpers` to a newly created file `modelArgs-helpers`. Because `schemas/objects/{model}Args` files should be generated if any of the two flags is active.
- Previously we were generating `_count` field whenever we found a model with `manyRelation`. But since the `isGenerateSelect` could be false, we will …
> Include support

- prisma/schema.prisma
- src/helpers/include-helpers.ts
- src/helpers/index.ts
- src/helpers/model-helpers.ts
- src/helpers/modelArgs-helpers.ts
- src/helpers/select-helpers.ts
- src/prisma-generator.ts
- src/transformer.ts
- src/types.ts
**Original bug:** Include was being generated for models that do not have relations with other models. A prisma client type that does not exist was being referenced in the generated zod schema.
**Fix:** Include is only generated for models that have a relation with another model. The referenced prisma client type in the generated zod schema exists for these models.
I added a model to our schema.prisma that does not have a relation to any other models (Book). This will help us catch issues like this more easily in the future, as we do not currently have a model like this in the schema.prisma file. 
Fixes issue: https://github.com/omar-dulaimi/prisma-zod-generator/issues/36
> Fixed bug: include no longer generated for models that do not have relations with other models

- prisma/schema.prisma
- src/helpers/aggregate-helpers.ts
- src/prisma-generator.ts
- src/transformer.ts
- src/types.ts
Hi @omar-dulaimi ,
I found another bug. Similar with #34 
In case your model doesn't have number type like this.
```
model Map {
key   String @id
value String
}
```
`prisma-client-js` will not generate `_sum` and `_avg` in aggregate type.
```
export type MapAggregateArgs = {
where?: MapWhereInput
orderBy?: Enumerable<MapOrderByWithRelationInput>
cursor?: MapWhereUniqueInput
take?: number
skip?: number
_count?: true | MapCountAggregateInputType
_min?: MapMinAggregateInputType
_max?: MapMaxAggregateInputType
}
```
So, I fixed this by removing `_sum` and `_avg`.
> Fix bug aggregate operation when Model has only string

- src/transformer.ts
Fixes the wrong groupBy schema caused by the orderBy field being optional.
> remove .optional from orderby

- src/prisma-generator.ts
- src/transformer.ts
Hi @omar-dulaimi, thanks for creating this awesome project. I would like to integrate a fix that is related to prisma preview feature.
https://www.prisma.io/docs/concepts/components/prisma-client/full-text-search
If we use `fullTextSearch` (one of the preview features prisma offers) with `MySQL` or `PostgreSQL`, then prisma exports `UserOrderByWithRelationAndSearchRelevanceInputObjectSchema` instead of `UserOrderByWithRelationInputObjectSchema`.
But in the transformer class while generating model schemas, currently we statically import the `UserOrderByWithRelationInputObjectSchema`. So I have added a resolve function that will return an import and zod-schema-line(like we do for include and select field) for orderBy field.
> Fix schema generation for prisma preview feature - fullTextSearch

- src/transformer.ts
Add `z.array()` on data property in `createMany<model>.schema.ts`.
This makes the zod schema conform to the prisma usage docs which requires a Enumerable around the input for createMany:
```
export type UserCreateManyArgs = {
data: Enumerable<UserCreateManyInput>
skipDuplicates?: boolean
}
```
closes #50
> Fix no array around createManyInput

- src/transformer.ts
- tests/issue-119-regression.test.ts
- vitest.config.js
Resolves Issue #119 by fixing three critical schema compilation errors:
- **SortOrderInput Schema**: Removed unnecessary lazy loading for simple enum references
- **Args Schema Types**: Fixed TypeScript compilation errors by removing strict Prisma type constraints for non-existent types
- **Required Field Validation**: Ensured all required fields work correctly (was already functioning)
- Modified `generatePrismaStringLine()` to use selective lazy loading
- Only applies lazy loading to self-references and complex object schemas
- Simple enums like `SortOrder` now use direct references instead of `z.lazy()`
- Modified `generateExportObjectSchemaStatement()` to handle Args types without Prisma type constraints
- Args types like `UserArgs`, `ProfileArgs` now use generic typing instead of …
> Fix: Resolve all schema compilation errors (Issue #119)

- README.md
Removes hardcoded version numbers from README to improve maintainability and prevent outdated documentation.
- Replaced specific version numbers (v1.0.0, v1.0.2) with generic terms (Latest, Current, etc.)
- Updated installation commands to use standard `npm install prisma-zod-generator`
- Simplified version compatibility table to use Latest/Beta/Legacy categories
```bash
npm install prisma-zod-generator@1.0.2
npm install prisma-zod-generator
```
- **Before**: Hardcoded version numbers that need manual updates
- **After**: Generic Latest/Beta/Legacy categories that stay current automatically
- Updated upgrade instructions to be version-agnostic
- Focus on dependency requirements rather than specific version numbers
- ✅ **Maintainability**: No need to update version numbers with each …
> docs: Remove hardcoded version numbers from README

- src/transformer.ts
- tests/typescript-inference-lazy-relations.test.ts
Fixes TypeScript compilation errors where required relation fields in CreateInput schemas were incorrectly inferred as optional when using `z.lazy()` for circular dependency resolution.
**Resolves the error:**
```
Property 'user' is optional in type {...} but required in type AuthAccessTokenCreateInput
```
The issue occurred when TypeScript tried to match inferred Zod types against explicit Prisma type annotations (`z.ZodType<Prisma.Type>`). The `z.lazy()` wrapper used for preventing circular dependencies was causing TypeScript's type inference to incorrectly mark relation fields as optional.
- **Added `hasComplexRelations()` method**: Detects schemas with lazy-loaded relation fields
- **Conditional type annotation removal**: Removes explicit `z.ZodType<Prisma.Type>` annotations for …
> fix: resolve TypeScript inference issues with z.lazy() relations

- src/transformer.ts
- tests/issue-118-output-directory.test.ts
- Fixes issue #118 where setting `output = "../generated/schemas"` creates nested `schemas/schemas/` directory
- Adds `getSchemasPath()` method to detect when output path already ends with 'schemas'
- Maintains backward compatibility for output paths that don't end with 'schemas'
- Includes comprehensive test coverage for both problematic and working scenarios
> fix: resolve output directory duplication when path ends with 'schemas'

- src/prisma-generator.ts
- src/transformer.ts
This PR adds comprehensive support for the new `prisma-client` generator introduced in Prisma 6.12.0 as a preview feature. The implementation maintains full backward compatibility while enabling seamless usage of the new generator.
- **Enhanced Generator Detection**: Automatically detects new `prisma-client` generator using provider name and config fields
- **Smart Import Path Resolution**: Applies `/client` suffix to import paths when using new generator with custom output directories
- **Multi-Provider Support**: Works across all database providers (PostgreSQL, MySQL, MongoDB, SQLite, SQL Server)
- **Backward Compatibility**: Zero breaking changes for existing `prisma-client-js` users
The solution leverages the generator configuration differences to detect the new generator:
- New …
> feat: add support for new prisma-client generator

- src/helpers/whereUniqueInput-helpers.ts
- src/prisma-generator.ts
- src/transformer.ts
This PR includes a set of fixes to the object schema generator:\n\n- Inline object schema exports to match CRUD style (no intermediate const).\n- Dual exports for object schemas: typed Prisma version and pure Zod version.\n- Bind aggregate input types to the correct Prisma `*InputType` variants (e.g., `PlanetCountAggregateInputType`).\n- Restrict `WhereUniqueInput` to only unique identifier fields and mark them as required.\n\nNotes:\n- Dual export flags still respected (`exportTypedSchemas`, `exportZodSchemas`).\n- Naming remains backward-compatible for existing imports (`<Name>ObjectSchema`).\n\nImpact: patch release (fix).
> fix: inline object schemas, add dual exports, and correct aggregate input bindings

- package.json
- src/prisma-generator.ts
- src/variants/generator.ts
- tests/schema-variants.test.ts
- vitest.config.js
Enums are not getting imported into generated schema files. This PR fixes this issue by detecting if enum field is being used in schema and accessing enum storages to import enums chema from prisma/client
i know that enum schemas are gettings generated too, but i think it's better to import them from prisma/client directly to be on more stable side 
how to check:
- generate prisma schema on master branch
- look into schemas/variants/pure/User.pure.ts
enum Role won't be imported automatically
> [fix] enums not importing to schema files

- website/docs/contributing.md
- website/src/pages/index.tsx
Fix Docusaurus build failure on CI by correcting invalid MDX/JSX in `contributing.md` and aligning homepage internal links with current docs routing.
- docs(contributing):
- Replace HTML `class` with `className`.
- Convert string `style="..."` to React style object `style={{ ... }}`.
- homepage:
- Update internal links to use `/docs/next/...` and avoid hard-coded baseUrl prefix.
- CI failed with: "The `style` prop expects a mapping from style properties to values, not a string" during SSG for `/docs/next/contributing`.
- After fixing, Docusaurus broken links check flagged homepage links that included `/prisma-zod-generator` baseUrl prefix. Adjusted to versioned paths.
- Ran `npm run docs:build` locally; build now succeeds.
- Docusaurus version: 3.8.1
- Node: v22.17.1 (local)
- Optionally …
> fix(docs): repair Docusaurus SSG and broken links on homepage

- src/prisma-generator.ts
- src/transformer.ts
- src/utils/singleFileAggregator.ts
Fix Prisma Client import path in generated Zod schemas when using the new `prisma-client` generator with a custom output. Imports now target the public `client` entry (e.g. `../../prisma/client`) instead of the directory root.
With Prisma v6 and the new `generator client { provider = "prisma-client" ... }`, the public entrypoint is the generated `client` module under the configured output directory. Previously, this generator imported from the output directory root (e.g., `../../prisma`), which lacks an index and caused `TS2307: Cannot find module` in generated schemas.
- transformer: compute Prisma import path relative to target dir and append `/client` when provider is `prisma-client`.
- single-file mode: ensure the inlined bundle imports `Prisma` from the `/client` entry when custom …
> fix(prisma-import): target Prisma client entry in generated Zod imports

- CONFIG_REFERENCE.md
- package.json
- recipes/README.md
- recipes/zod-imports/README.md
- recipes/zod-imports/zod-generator.auto.json
- recipes/zod-imports/zod-generator.v3.json
- recipes/zod-imports/zod-generator.v4.json
- src/config/parser.ts
- src/config/schema.ts
- src/generators/model.ts
- src/prisma-generator.ts
- src/transformer.ts
- src/utils/singleFileAggregator.ts
- tests/zod-imports.test.ts
- website/docs/recipes/zod-import-targets.md
- website/sidebars.ts
Add `zodImportTarget` configuration to control how generated schemas import Zod. Supports:
- auto (default) or v3: `import { z } from 'zod'`
- v4: `import * as z from 'zod/v4'`
Applied consistently across multi-file output, single-file bundles, and JSON helpers.
- Allow users on Zod v4 to opt into the `zod/v4` subpath for better tree‑shaking and explicit versioning.
- Keep default output compatible with Zod v3 style while remaining valid on v4.
- Clarify dependency story by declaring `zod` as a peer dependency (`>=3.25.0 <5`).
- Config
- `src/config/parser.ts`: Add `zodImportTarget?: 'auto' | 'v3' | 'v4'`.
- `src/config/schema.ts`: JSON schema validation (`enum`, default `auto`).
- `CONFIG_REFERENCE.md`: New section “Zod import target”.
- Generator
- `src/transformer.ts`: New …
> feat(zod-import-target): add zodImportTarget config and update imports across generator

- src/transformer.ts
- tests/naming-customization.test.ts
- adjust the CreateMany pattern recognition so aliasing keeps the owning model name
- add a regression test that exercises nested CreateMany generation via naming customization suite
- running `pnpm gen-example` followed by `pnpm typecheck` produced missing export errors because generated schemas aliased imports using the related model name (`UserAccount...`)
- the regression blocked consumers from type-checking generated output after enabling nested Account relations
- tighten the regex used by `extractModelNameFromContext` for CreateMany inputs to capture the owning model prefix
- introduce a dedicated test in `naming-customization.test.ts` that generates a minimal User/Account schema and asserts the generated imports retain the Account prefix
- `pnpm typecheck`
- `pnpm vitest --config …
> fix(transformer): use owning model alias for create many imports
